### ISSUE TITLE
Deeptrack import error: Issue with loading deeptrack.models

### ISSUE THREAD

**Issue by Konccept** [DeepTrackAI/DeepTrack2#208]
Just general information about my system.
I use an M1 Mac. Installed Pytorch using:

`conda install pytorch torchvision torchaudio -c pytorch-nightly`

This a fresh install in a fresh Anaconda environment, due to prior issues with torch sparse and torch scatter.
I installed deeptrack using:

`pip install --pre deeptrack`

`import glob
import deeptrack as dt
from skimage.measure import regionprops

sources = dt.sources.Source(
    image_path = sorted(glob.glob(os.path.join(dir, "02", "*.tif"))),
    label_path = sorted(glob.glob(os.path.join(dir, "02_GT", "TRA", "*.tif"))),
)

image = dt.LoadImage(sources.image_path)[:, :300] / 256
label = dt.LoadImage(sources.label_path)[:, :300] >> regionprops

pipeline = image & label`

Upon importing deeptrack, I get this error:

`ImportError                               Traceback (most recent call last)
Cell In[2], line 11
      5 sources = dt.sources.Source(
      6     image_path = sorted(glob.glob(os.path.join(dir, "02", "*.tif"))),
      7     label_path = sorted(glob.glob(os.path.join(dir, "02_GT", "TRA", "*.tif"))),
      8 )
     10 image = dt.LoadImage(sources.image_path)[:, :300] / 256
---> 11 label = dt.LoadImage(sources.label_path)[:, :300] >> regionprops
     13 pipeline = image & label

File /opt/anaconda3/envs/ML/lib/python3.11/site-packages/deeptrack/features.py:526, in Feature.__rshift__(self, other)
    522 from . import models
    524 # If other is a function, call it on the output of the feature.
    525 # For example, feature >> some_function
--> 526 if isinstance(other, models.KerasModel):
    527     return NotImplemented
    528 if callable(other):

File /opt/anaconda3/envs/ML/lib/python3.11/site-packages/lazy_import/__init__.py:156, in LazyModule.__getattribute__(self, attr)
    151         logger.debug("Proceeding to load module {}, "
    152                      "from requested value {}"
    153                      .format(super(LazyModule, self)
    154                              .__getattribute__("__name__"), attr))
    155         #traceback.print_stack()
--> 156         _load_module(self)
    157 return super(LazyModule, self).__getattribute__(attr)

File /opt/anaconda3/envs/ML/lib/python3.11/site-packages/lazy_import/__init__.py:536, in _load_module(module)
    534     raise
    535 msg = modclass._lazy_import_error_msgs['msg']
--> 536 raise_from(ImportError(
    537     msg.format(**modclass._lazy_import_error_strings)), None)

File <string>:3, in raise_from(value, from_value)

ImportError: deeptrack attempted to use a functionality that requires module deeptrack.models, but it couldn't be loaded. Please install deeptrack and retry.`

**Comment by JesusPinedaC** [comment]
Hello, we have identified the issue and it will be corrected soon in the next release.

In the meantime, please install deeptrack from the develop branch where the problem is resolved. 

This can be done by running: pip install `deeptrack@git+https://github.com/DeepTrackAI/DeepTrack2`

Or cloning the repository and executing `python setup.py install`.

**Comment by naiikaa** [comment]
Hello!
I had the same problem and tried both your suggestions but still get the same message of 
`ImportError: deeptrack attempted to use a functionality that requires module deeptrack.models, but it couldn't be loaded. Please install deeptrack and retry.`

I'm trying to import LoadSTAR when this error occurs

**Comment by BenjaminMidtvedt** [comment]
@naikaida Hi! Can you tell me the OS, python version, and deeptrack version you are using? Preferably also some short code-snippet that reproduces the issue

**Comment by naiikaa** [comment]
@BenjaminMidtvedt 
```
OS: Ubuntu 22.04.4 LTS x86_64 
Python version: 3.10.12
deeptrack version: 2.0.0rc0
```

I create a minimal .py file to recreate the error. Running this two lines:
```python
import deeptrack as dt
model = dt.models.LodeSTAR(input_shape=(None, None, 1))
```
results in the following trace:
```
/usr/local/lib/python3.10/dist-packages/deeptrack-2.0.0rc0-py3.10.egg/deeptrack/scatterers.py:100: SyntaxWarning: "is not" with a literal. Did you mean "!="?
/usr/local/lib/python3.10/dist-packages/deeptrack-2.0.0rc0-py3.10.egg/deeptrack/scatterers.py:100: SyntaxWarning: "is not" with a literal. Did you mean "!="?
Traceback (most recent call last):
  File "/home/npopkov/deeptrack/notebooks/dash/recreate_error.py", line 3, in <module>
    model = dt.models.LodeSTAR(input_shape=(None, None, 1))
  File "/usr/local/lib/python3.10/dist-packages/lazy_import/__init__.py", line 156, in __getattribute__
    _load_module(self)
  File "/usr/local/lib/python3.10/dist-packages/lazy_import/__init__.py", line 536, in _load_module
    raise_from(ImportError(
  File "<string>", line 3, in raise_from
ImportError: deeptrack attempted to use a functionality that requires module deeptrack.models, but it couldn't be loaded. Please install deeptrack and retry.
```

**Comment by BenjaminMidtvedt** [comment]
@naikaida It's possible some tensorflow dependencies are missing. Could you verify that tensorflow is installed?

**Comment by naiikaa** [comment]
@BenjaminMidtvedt 
yes thank you that fixed the import error.
__edit__ : no problems with loadSTAR. i was following an 'old' tutorial
